### ISSUE TITLE
Expose types

### ISSUE THREAD

**Issue by AydanGaite** [unlocomqx/svelte-apollo-client#1]
Currently I can't import type declarations unless I copy them into my own declaration file.

**Comment by unlocomqx** [comment]
Which types are you trying to import?
Can you share a code sample?

**Comment by AydanGaite** [comment]
I want `ReadableQuery` from the `svelte-apollo-client` declaration file so I can strongly type `query` instead of inferring it.

**Comment by unlocomqx** [comment]
I exported the types in `0.1.0`, you can import it using
```ts
import type { ReadableQuery } from "svelte-apollo-client";
```

**Comment by AydanGaite** [comment]
Perfect thanks
